### PR TITLE
Added Today View Widget

### PR DESCRIPTION
**Pull request by BlackWolf**
Took the liberty of adding a widget for the "Today View" of Notification Center. 

I tried to keep it as small as possible, so currently it can:
- Show the current and next show
- Open the stream on click

Note: It seems that Today Widgets in XCode are still a fragile little thing. For example, I do get an error when I try to run the app while another instance of it is already running. Sometimes I need to compile 2x for the widget to update in the sidebar. This might be due to caching issues, but I thought it should be mentioned here.

### CODE REVIEW

**Comment by timoschlueter** [comment]
Great idea! But is it really necessary to redeclare the parseICS() and isConnectedToNetwork() methods? Can't we use the methods already there? Or is this necessary because "Today View" Widgets are completely separated from the main application?

**Comment by BlackWolf** [comment]
No, you're right. I should have mentioned that this was done pretty quickly, the code needs to be refactored in the future. 

The apps are separated (since the widget can run without the main app), but we can use .swift files for both (as, for example, I did with `ProgramPlan.swift`). So basically this means we need to refactor the methods needed for both into a separate file.

If I have the time, I will do that today, but I can't promise.

**Comment by BlackWolf** [comment]
as a heads up: i am working on the refactoring, its just a little more work than I though... just praying noone will commit anything before I'm done :D I hope I can commit it tomorrow

**Comment by timoschlueter** [comment]
Take your time. I won't merge pull requests until you are ready :)

**Comment by BlackWolf** [comment]
So here it is. I did a rather large refactoring, the most important things are:
- `ProgramPlan` is now called `Program` (as it represents a single program)
- The properties of `Program` have been renamed and some changes were made. The full title is now stored in `rawTitle` and the parsed title parts can be accessed using `title()` and `state()`. `iconName()` returns the icon name :-)
- A new class `ProgramPlan` is now responsible for fetching the program and reporting back to its delegate using `programPlanDidRefresh:`. This class is can be used by the main application as well as the today widget. 
- Changed font color of times in the main app to adress #25
- A number of other minor stuff

Please test this before you merge it :-)

**Comment by timoschlueter** [comment]
I just took a quick look into the code. Looks good so far :)
Needs a bit more testing before i merge it into master branch though. I hope i have the time to check it after i get home from work today.

**Pull request merged**
